### ISSUE TITLE
Laser/lamp state available on NZ series projectors?

### ISSUE THREAD

**Issue by blackgold9** [iloveicedgreentea/jvc_projector_improved#20]
On the NX series, the lamp state of off/reserved/on/cooling was super helpful for automations when starting up/shutting down, and knowing when the projector was ready to receive inputs (lamp was on).

Is a similar thing available with the lasers?

**Comment by iloveicedgreentea** [comment]
Yes it is part of the PowerStates class in this library. Its not part of the laser state for NZ models. It can be accessed with the _get_power_state function.

What are you trying to do? When the NZ reports on, it should be ready to accept commands. In HA, I have a wait template to wait until the state of the NZ is 'on'

```yaml
{{ is_state('remote.nz7', 'on') }}
```

**Comment by blackgold9** [comment]
I had automations to do things like slowly dim lights when the projector is warming up, or bringing them back up as it cools. Honestly the warming up bit is most valuable to me.

**Comment by blackgold9** [comment]
I am.

**Comment by iloveicedgreentea** [comment]
Okay the NZ series only expose "cooling" but takes only a few seconds to actually cool. There is no warming state. It basically goes from off to on to off. I would suggest triggering lights based on a script which is activated by your remote.turn_on/off actions since there is no way to see if the PJ is warming and cooling might not be reliable.

**Comment by blackgold9** [comment]
Fair enough.  I have a challenge using the ha component, but I'll cover that in the right project. Thanks for the help!

**Comment by iloveicedgreentea** [comment]
Okay if you want help with the HA please feel free to open an issue there and I can try to help you

**Comment by rob-cohen** [comment]
> I had automations to do things like slowly dim lights when the projector is warming up, or bringing them back up as it cools. Honestly the warming up bit is most valuable to me.

That's a neat idea to slowly dim as the projector warms up. :)
