### ISSUE TITLE
Add Lamp Time and Software Version

### ISSUE THREAD

**Issue by kernelpanic85** [iloveicedgreentea/jvc_projector_improved#21]
Great JVC integration!  Do you think it's possible to add read commands for Lamp Time and SW Version so they can be exposed as sensors in HA?  I peeked through the JVC docs and it seems they are available:

![image](https://user-images.githubusercontent.com/80057019/233182369-2309da44-7405-424a-93a6-88d40586ff2e.png)

http://pro.jvc.com/pro/attributes/PRESENT/manual/2018_ILA-FPJ_Ext_Command_List_v1.2.pdf

**Comment by iloveicedgreentea** [comment]
Sure I can add that

**Comment by jkeljo** [comment]
I was adding some other commands and came across this issue, went ahead and put up a PR for these ones while I was in there.
