### ISSUE TITLE
FW 3.0 0-100 Laser Power Levels

### ISSUE THREAD

**Issue by rob-cohen** [iloveicedgreentea/jvc_projector_improved#25]
Firmware 3.0 added support for laser power levels of 0-100.

The old LaserPowerModes low/medium/high still works fine with this library, but it would be nice to be able to have more granular control without going through multiple levels of menus.

It shows up in the OSD as "LD Power".

Thanks!
Rob

![image](https://github.com/iloveicedgreentea/jvc_projector_improved/assets/21690092/19c67da5-5f1a-4d59-b726-46d15d450686)

**Comment by iloveicedgreentea** [comment]
If you can get me the command to run or the remote code I can add it. I can't find any updated spec from JVC. Command would be like  PMLP. It would have a specific kind of input as well, probably numeric.

**Comment by rob-cohen** [comment]
Some details here:
https://www.avsforum.com/threads/official-jvc-rs4100-nz9-rs3100-nz8-rs2100-nz7-rs1100-np5-owners-thread.3226551/post-63154737

It's nothing critical, since this can currently be controlled with picture modes. There are occasions when it would be nice, though. Of course, on those occasions, I can also navigate a few menus. First world problems. :)

**Comment by rob-cohen** [comment]
Hmm...on p34, it looks like this only includes what you have already implemented. I didn't find more granular control.

**Comment by rob-cohen** [comment]
Then again, it looks like he has highlighted a numeric command PMCV on p27.

**Comment by rob-cohen** [comment]
Another low priority but would be nice feature...
Showing the source format on p41.

Similar deal. On occasions when I need it, I can go into menus, but it would be convenient to display on my HA control panel.

**Comment by rob-cohen** [comment]
Actually, looking closer at this stuff, this one would be more useful and probably easier:
Reporting the current anamorphic mode status.

It's often confusing to know what's going on when the aspect and anamorphic modes aren't right, and it would be very helpful to be able to see it at a glance.

As a binary sensor, when you select it as a button, it will show as the button state.

    binary_sensor:
      - name: "JVC Aspect Auto"
        value_template: "{{ is_state('remote.nz9', 'on') and (states.remote.nz9.attributes.aspect_ratio == 'auto') }}"

**Comment by iloveicedgreentea** [comment]
Okay I added all of these. Please test 4.1.3 of the integration. I didnt update to fw 3.0 so I can't test the laser value yet but it should work. Source format will appear under resolution.
